### ISSUE TITLE
Can't start module [TypeError: httpProxy.RoutingProxy is not a constructor]

### ISSUE THREAD

**Issue by xardbaiz-zz** [pouyajoon/node-reverse-proxy#2]
_There;s_ must be problem with httpProxy dependency

```
npm start

node-reverse-proxy\node_modules\node-reverse-proxy\lib\node-reverse-proxy.js:5
  this.proxy = new httpProxy.RoutingProxy({ router: router });
               ^

TypeError: httpProxy.RoutingProxy is not a constructor
    at new node_reverse_proxy (node-reverse-proxy\node_modules\node-reverse-proxy\lib\node-reverse-proxy.js:5:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by jrichardsz** [comment]
October, 2018
Same error!
